language: java
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: ipqrM8DnH61X14tfBSL2L+dPJalPCklDbXFWxXteY5wd2EMZS78WP+/pjdaZFbTDfKOrlSOrVZm59Pc4Z6FEOt26djVaTeSo6qaCppfg6CW3OvW52WXYTLkD4JoxruJuZ4HRW4jfbfS+oTkHg0ZZz/56++BDlBfbVxj/aGeR9MUrmevUWVrG6Os/Gu+PJrUb78uZcRefCJhBMIuF8MN097wFBVYERiikudfhRNo5AD4PSzXv7ORZ6+sqqr/MWHfsqm/S/j1xRfjCw7UFTYsYLkzaL9xN+Zu3hQNrIsWQGzROdLH+keuAcbUUae5SEC/25nePdC+28HKnqUGGJxrjYzTMysyugMya52UJ7nrGFxLZAny5k+16C0Kro5eWKK+K/0TrE58Z60AQBJj9Yg8UuFcmVzJ0UptzQpMs1gLq6F3UUaPHviXCdVp01eQuCjKIvjl3fMYC2riqO+ePSWRvEg8u5JJxtV+iV15I3uXdFHp4HlDlH9WXs0eB6P1zJueQO6xFTaGNu3HqMfhll6b8h4IlPCDfd8RO4gUMJzVSuQJDODPg+E8JtIyrzX0GwTWyUGJQ4MJKaPjzBPdiZhPOghyTodrwUYgSuwQx8PlezMYtn2r0yCuVeOX1uM5k14ZpHYPiecajcseetF/vhIADmiwAZX1mJy36wN/OyhoXqtw=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-teamcity-plugin
notifications:
  slack:
    secure: D+oL2v72lveBMgrtL+PZl4MLiagTB34GJRb2OF4h8ossezGne+r+WtVBDDeKcxyWl6faroDl8OEBCRLxBk0JXBrqmAZUuriK62VdW0P6UPmw/imQp7k5YgIUxoBIXJLCREkW6xXrZ7iLgm2M3mnWxEY1FRDIj1qyKJcHiuICB3VQTK3iG76GpdBBMDVSC9NyPHUtHtHcZSnsOosyZ/+q5K5mxtuZ3TuUO6sMwkh0wclzRjDonLWMDhlX7ul+N8RrKSst8cs9EQ1YiYVXJ1Og4fv5HUELFBbrfdSMiQE55CfSSsmfjIimksNCCMfGDGgrnXMMY5AZPZnnYKq4ym/LUWZ8eUi3sSHa8+QsTUudawrjd0dNd4kObwEhuDJhRJSmePxF/t0wF4/wdcF4CFFC8m2Onw0XLM9403bn9NIU56GD29XxZ9HsDfHHNrkM6M2IL3gIevHZHhQbvkaekFRvYSR2Tj0EZ5nwysxrocTnCUY3tuYLEWOkGLudahGIiIH1LAZpzNvlErf+2zDY3Xqw6zVub2rFFUSYfM7bhIPTakADX4BMJ+Cb2xI0pBbvWCoxmdVZ8LXzQN5h3ZZ8hOymSRX37KGr7md35BXSyE2/GrZdblNSGQWVzR1Xba/vXroPP6DWcX68tFkadK2xov11l0sOqGa+td3OFwvL8AS+CpI=
