language: java
deploy:
  provider: releases
  api_key:
    secure: KK4YcZ9EKIrEqpfmZGmFk+obfk2c+BnEA1bQ+sbUJD3VqgTcotFWEsByRH9YmP1ZHVlKCQSfhtEjVTbnAMS6tbMPusLNy4nUTUx9qtUrAsr0LEt2z/Q76GUuuDs1/cU95lDm7FODXjt3rrhsYqiCIqGNBRT+IXyF/pqfyswgStTq0SV6PP9t4h+RTJvrw85X8d0IscqT88p3mwprwWlsl+Rlt6SJdbBCYDvUoC/YaBXT+c1/Qt31QK0W45h4JdctaBqS6BVTYMqnn9tQY3YIxEzSu6t1dGmHTN3wbMonp8+I25b+zfbt1NKgq+aM4Nc6PKbQlERvDRYsYqCvyVZlZ0MsAUGC4N1fOChXXpS3mmEdesjDJbX2TpxNf/Dpm23Tag5kCuSSwT1fsxnZv+WlCEhyoBM9YTqucE6o2U+Nv9vveYyA2cl4AJR8IMiA8ycfX2SVkEnkYBUR+p3wlSv70dvwrH2ahZhN12SYH+ZVrmo4VwTY/rOL6+z2tuyshUNH8nT5sIT8Fs1U9QQgkhAUr0v+SlVJ2oeJ8Nx0auaWAKuP2qHIrAeaL4lrdX6jP7Qgzijpm6P+Na5QCwIRCnj1/5niPLcsxovRPLJ0lIpKn9a03j8RqBWKnmntHpJyXNuBb4hHgeTpHym+Z+t4tydwPpy/ehCaFXpSRbbr9br+/74=
  file: build/libs/xlr-teamcity-plugin-1.0.2.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-teamcity-plugin


