language: java
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: releases
  api_key:
    secure: f9mWmvRmAahA6kEHMJFlkkslfhMIAli0Sv5Lpw6U8bxDzPaE/4DxHlSXSsN8NP9aI/iOWctCzH1KKQMBE6/B9uDe5pjb7AeoO09tbaokNfEv29NREg9MHpOrAQXSC9abZv6iIli2Kaz4Smxt05C5yjN2oWA6pKfJ+gQFpCbj6DKHBoc0z/C9lzW9AS+84+S6bsFlpfgI+rIgOpUiieuuZo9r6Oq7Ddb91B8Pq3DnGw9midExVFX7B4Vym/TNU+VJOq0N29ZSfXd14Ckm3fvKkXfZkqdF2Ha7x42zyGm7fUJax3dKDLt0NBLM0vOsIrInlA+X6qk37+4zR4XLE+bo8OYXijrNE8+slcCi5Qb74GztNU92vR2Bphg2N2bg4aSp+pwMaLsdHmWKyMXQ3IkkHCMiIYG03AMXbARuXaorcdSmxr2mz6ajUs4QJslGlg77uyb0SOkJZWQU0k3gDi77reNl4Pw8xQi7p8pR7CfxcIGql1h+5O6jt08cXfxm49Ae0FzuLCdSrDz2iPWK65jUtuZhPYlWC/0rQMwsB91JFans40tQ44+vH+J4Gvg0rn6FZuFnO9u8hqqO3O/6A/ZCgyyFd8jJgUlhVIlyfLhMgCsjb1oRKTT03+1CZL/nFDdVDuWuwtrMPfJ43Ijh71vVepiqGVcZ1kGj0ChyLiREPrk=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-teamcity-plugin
notifications:
  slack:
    secure: D+oL2v72lveBMgrtL+PZl4MLiagTB34GJRb2OF4h8ossezGne+r+WtVBDDeKcxyWl6faroDl8OEBCRLxBk0JXBrqmAZUuriK62VdW0P6UPmw/imQp7k5YgIUxoBIXJLCREkW6xXrZ7iLgm2M3mnWxEY1FRDIj1qyKJcHiuICB3VQTK3iG76GpdBBMDVSC9NyPHUtHtHcZSnsOosyZ/+q5K5mxtuZ3TuUO6sMwkh0wclzRjDonLWMDhlX7ul+N8RrKSst8cs9EQ1YiYVXJ1Og4fv5HUELFBbrfdSMiQE55CfSSsmfjIimksNCCMfGDGgrnXMMY5AZPZnnYKq4ym/LUWZ8eUi3sSHa8+QsTUudawrjd0dNd4kObwEhuDJhRJSmePxF/t0wF4/wdcF4CFFC8m2Onw0XLM9403bn9NIU56GD29XxZ9HsDfHHNrkM6M2IL3gIevHZHhQbvkaekFRvYSR2Tj0EZ5nwysxrocTnCUY3tuYLEWOkGLudahGIiIH1LAZpzNvlErf+2zDY3Xqw6zVub2rFFUSYfM7bhIPTakADX4BMJ+Cb2xI0pBbvWCoxmdVZ8LXzQN5h3ZZ8hOymSRX37KGr7md35BXSyE2/GrZdblNSGQWVzR1Xba/vXroPP6DWcX68tFkadK2xov11l0sOqGa+td3OFwvL8AS+CpI=
