language: java
notifications:
  hipchat:
    rooms:
      secure: OlIO4DA0xfqdHqS2ytSfDucjIoncHBgLDFjDi1u+qsLOPBeYpYuNJOZkW531yKPFS/na8BjS5WzjrdZW1Wa2I41X2KdNEqOBPxCNsDlvRzEsMUXGCekTEkIaVKgyD8LsAqku+I0CFRsYCQCxRz6yufEenDf7VwdhbM/345mopkI=
deploy:
  provider: releases
  api_key:
    secure: Hn6IT9//1ayaPmiDYFpaiGFUHaDkZWHIHxNqt7RNZgvk6WqupgQxx1qCi8H7kNUjP6Cwpkob0T6tLWEb3NttwKehi+hAzPSeqoGRfyVdquCB4SWyrf0imayMqWNlt1iiqtMoGeh7BsttncAIZxO/tCYifO3wQjW+pCl7fZM7GNj9FiXywdJ8ZV/GNGFSDlKJRXSUl5CxD6JMXTGyELV/9EAnEzlBtDzJgF0FL38CZTL0oVmir2H9re+SMDgvJvBEL5p/mlrGeisdFK24mHM4i6B9jTVpgq214zajLfnFrAohSu3dGalhWM6ViBML1xRtR4EAGYBx+gDBbN9oDpxTSXIvSUykgUalso0b4s8rque49G64aaG80+PCKkABixtpR3UVupqB3clPiqZ795OGPeZ9Ge4i9y9M83XCCxJbjzQSnf5fVoy9xJ4OEEb2l2J2Sjs5WXfOPG3xlxEKnOGSsaD/tifXm4EVvoj6RoY9LAWvLJ/asgpklsz7nFSQbwCkYTeSc6k26LzcRSzwB6e/zzuR2WjptvdSCZRI2MCjBly59/bk5g74gNNp3OmuJ+K+4LgnCn8nX2JENXPWlWM23K8kLXWdMyL6lNUusEWtgRXCaCs6oF8uyE6pawlW+G9FdbSaAaqC6lfMZ66anO+CiSVewBqy909/iVYzUJ70FFw=
  file: build/libs/xlr-teamcity-plugin-1.0.2.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    repo: xebialabs-community/xlr-teamcity-plugin
env:
  global:
    secure: Hn6IT9//1ayaPmiDYFpaiGFUHaDkZWHIHxNqt7RNZgvk6WqupgQxx1qCi8H7kNUjP6Cwpkob0T6tLWEb3NttwKehi+hAzPSeqoGRfyVdquCB4SWyrf0imayMqWNlt1iiqtMoGeh7BsttncAIZxO/tCYifO3wQjW+pCl7fZM7GNj9FiXywdJ8ZV/GNGFSDlKJRXSUl5CxD6JMXTGyELV/9EAnEzlBtDzJgF0FL38CZTL0oVmir2H9re+SMDgvJvBEL5p/mlrGeisdFK24mHM4i6B9jTVpgq214zajLfnFrAohSu3dGalhWM6ViBML1xRtR4EAGYBx+gDBbN9oDpxTSXIvSUykgUalso0b4s8rque49G64aaG80+PCKkABixtpR3UVupqB3clPiqZ795OGPeZ9Ge4i9y9M83XCCxJbjzQSnf5fVoy9xJ4OEEb2l2J2Sjs5WXfOPG3xlxEKnOGSsaD/tifXm4EVvoj6RoY9LAWvLJ/asgpklsz7nFSQbwCkYTeSc6k26LzcRSzwB6e/zzuR2WjptvdSCZRI2MCjBly59/bk5g74gNNp3OmuJ+K+4LgnCn8nX2JENXPWlWM23K8kLXWdMyL6lNUusEWtgRXCaCs6oF8uyE6pawlW+G9FdbSaAaqC6lfMZ66anO+CiSVewBqy909/iVYzUJ70FFw=
