language: java
deploy:
  provider: releases
  api_key:
    secure: XsqYdr9Wjzg8ed21vLvotqn9IB8wLWii9yd0ebClTdMsW02qcN31bKh3EIU7tc82sTCg99hFXIZKo/fR7fVaUVRuT24X/c5BZcREK71fkAPfuxOFk1LDwZZku9rWgrX1Qg/lGmlpfZH3yZdjbDlnakHW621mbTOEVCN+/VLZnFB9yTsBorxW20WIQJFq9cZdKjwPN73ckmrSrV2PIsc/egjGASFZ2z+FAIweY+5nmQlvW4UIhKYH+iGMEoGJg/PIkrJIIMd3ZO8Z2RaoEnyHAUrn1RP+IAGSxZ/zr4acvPWMQe1gzPFl8/a8c/Apu/gq9XYYwPLqehjQ0dr2nH3dI4LQjp+4LUG/grLaVT80gi0Gy1L7WXla/wmxqhZ5/x6BG0WzAeeLyJNuUIOtovhAT6F5mzl5cNqmxYqrT65od4CqCSSUnozybQrfyj0KoySYP71mZim7Au6DwWTkIKoHQB1VOvPIMibW1SuvTzheaIpYn6WPzZM2y4mkoczZ7h11YULN61OAr7cy5tkbi7xGFjnp4fYTuHCKfpgUi6A2LfkqZKOOutfii9Q09ZCEvjPjxUnr6fQ9b1rpqkhZ8e9Gurg2DuOGdsuY/Y2RJEtpi+HOg0eSRKKD21ng3UqcBAqKBuMEWVTpmse4bJEBA+8Wsy6ezYY15Cd0kEIAGp2VgIk=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-teamcity-plugin
notifications:
  hipchat:
    rooms:
      secure: pPsyCShs7Z8aD+wpWV4xeCz69btpvGl6pXp00sx8F3421t7WZWDFUS9YnjN8gmXLdJYu3+YR5Mh4o7Zbmvnlii6avH0fNCWzw9AMIgFW9/VOYpmCKA4F+Oq4HPP6hKUwDk3Dvl4O/yMrW0/2jqv2OCXUbtQKauJC755cFXVlyL5rdnGDvSmidC2Y72nt5j6Ty5q1ekpjf33znzUrPPfZSUyKU/gzFI3n1aDTXU34aNT+ELq2KBa6Jj9xDsHIyg3g6sKGI93nHrI7d/8YDk4IiNBnr7rFZjbevmQdCsOF90aO6X9Z92jIXjXRcCNyH7vh9m3Nod5xvklfZ8CckDKyIhwqE9Dq8PIjAfavdvcRiDYeDJa2u4rEfxOw3LyiWL4UIs3bcDsLsnFXzzwzdIq7LOnom2Oy82vvA0VgOYFrYDsU1cDaSkVdHDxlgqIWtOmMLbE7s4lLQLgYMe/fPCEBj4izSMGhS2zgfTByF5wM2PggEJAUMo0AHt4QYk1WxiUe2AVluNCaLqx4+cZXGV66l8KY0Bi1ZvsOjy5dFE9CGaKhUOUAN0/toYczTKNRKGuu0MmJqiMZ9gi5Mv+CWNv30xBQc6HTYGmmLUfv1trckK1Hs4RIcL4r5MlUfwoIUGgtCXdqDLSaKNWZryXZLiysc4R0WacCqk9Kod2HvC09GPs=
