language: java
notifications:
  hipchat:
    rooms:
      secure: OlIO4DA0xfqdHqS2ytSfDucjIoncHBgLDFjDi1u+qsLOPBeYpYuNJOZkW531yKPFS/na8BjS5WzjrdZW1Wa2I41X2KdNEqOBPxCNsDlvRzEsMUXGCekTEkIaVKgyD8LsAqku+I0CFRsYCQCxRz6yufEenDf7VwdhbM/345mopkI=
deploy:
  provider: releases
  api_key:
    secure: oJuUAq2yr5kdP/BOzh8PQ0nC3YvRzfnEdHDaX/9DA2MiTQBgOrOPgU38Z7zMhFdKHC6RWUKwXAtGOUec4pICaQJozOhPgz0HvjtTwQx/Asi9FDxRJa0fGREl/y0TdT76KZ5o7Jbo2TGDBRq3KMKQ8cQmj57bd7qvuwCcc2BeQ9JIZ8SYzWt+gfZksbIwxxdPy01b/g5jUjxtPX+dkcFy5V2Uj8wOyVuoicWs5gZcmF9VhNZQNZHKgz+WZMvxrHm7zpuge7P8D5bPOld9yiNxPwbKAnTqgCPcquqmrcDGkAky7rvZae5pVg79+JGUhSVMam9rWEBO7CRNs3t5KRrYP6dOJL4fpSYNRK8y8Hh2NtOcPiDDSPT8cnVPHj1WbC3kbbI5JP5CSrV1xn6KFWkincfjZ05XXO+Nv+5dk7rohJi35uaizwFKDD6cJAmZM8IDQLhu7u4qOj/07P5w9XsKTqCx0EQS2qvSHHd3khWfIp2/9n7gpW73/ElM/s2PGSxkSPZPJXYwm8SUCXyniJldkpHdRX/AgraaJ0NcMbTb9ifDsmTvsUUIo9lr1wDwsZtXcleT3Wc8oIdazy+Y9J9OPirAmOSXRansou4apWZfRyX/GT4Kch8qiyG4ZLymxaKU4wjuRokZb+WU6osZcQzj6Czu2I7LtFwKZ2+4vpzhoik=
  file: build/libs/xlr-teamcity-plugin-1.0.2.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    repo: xebialabs-community/xlr-teamcity-plugin
