language: java
deploy:
  provider: releases
  api_key:
    secure: Qq//AQ6f6s1SFF2dlMBYUKPcUkVgeJz9hnFw0HPoCUaKlQeXBZa6RBZXZFh3vnZ3Gc9YSPir/uLbO23XMrVdPjc8N9e4D7sWj6yqMa5HQzwjQmlc9i5fPvBIm/8CclA6cpiRaXtpQML4KPMX6YkzVGw8s+jM+noMisX5d2qkouobyrplsf2+QDYRlHIfynrNPXFbJ4XlOijVAfYPNsJzjkQ1ki9kt6WIqm5dpfygTtjQg/rrEeRuUdNg+chvmIZOQymTiXPFTAEtkN8br6jDt+Plpu8DfKIVfyWPPiHVelgDMZ1hEnBA0g3LSVhiN7pg+FsO/ELDtIyL5jhGutWhwNeMqN0P0N5u1JmDVwAHKyBJNEEcAhihR2HN5RQtz8OPJiVtcvQPBAAFlahvf92VISkGi1nzHFAY4gJZMNa2SlGQ44jKkSfn8wGVhrWbQxUAaG+Vpu2dfDL8Wp8c0ZMcCMY7YJO8XilDcPy1E1ojoyN537KjdPUHhohuu1NFKySEfOx4uahNZUiO+FXxXr7QF7W/Kkuhfh/jnVndvQPZ+TMZGZD16wGrM2ZZ+GGl6+JfJJ/OnK6TZS58hnRc31mTXDcJnHZl3nu3QmhZgcwnFTKzSpFmVpizyMBtt+elpsUD3bfHYr6U/ESnTFRSLK1ObxyxzhO5lHnqAqtNGHeCOME=
  file: build/libs/xlr-teamcity-plugin-1.0.2.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
repo: xebialabs-community/xlr-teamcity-plugin
