language: java
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
deploy:
  provider: releases
  api_key:
    secure: XsqYdr9Wjzg8ed21vLvotqn9IB8wLWii9yd0ebClTdMsW02qcN31bKh3EIU7tc82sTCg99hFXIZKo/fR7fVaUVRuT24X/c5BZcREK71fkAPfuxOFk1LDwZZku9rWgrX1Qg/lGmlpfZH3yZdjbDlnakHW621mbTOEVCN+/VLZnFB9yTsBorxW20WIQJFq9cZdKjwPN73ckmrSrV2PIsc/egjGASFZ2z+FAIweY+5nmQlvW4UIhKYH+iGMEoGJg/PIkrJIIMd3ZO8Z2RaoEnyHAUrn1RP+IAGSxZ/zr4acvPWMQe1gzPFl8/a8c/Apu/gq9XYYwPLqehjQ0dr2nH3dI4LQjp+4LUG/grLaVT80gi0Gy1L7WXla/wmxqhZ5/x6BG0WzAeeLyJNuUIOtovhAT6F5mzl5cNqmxYqrT65od4CqCSSUnozybQrfyj0KoySYP71mZim7Au6DwWTkIKoHQB1VOvPIMibW1SuvTzheaIpYn6WPzZM2y4mkoczZ7h11YULN61OAr7cy5tkbi7xGFjnp4fYTuHCKfpgUi6A2LfkqZKOOutfii9Q09ZCEvjPjxUnr6fQ9b1rpqkhZ8e9Gurg2DuOGdsuY/Y2RJEtpi+HOg0eSRKKD21ng3UqcBAqKBuMEWVTpmse4bJEBA+8Wsy6ezYY15Cd0kEIAGp2VgIk=
  file_glob: true
  file: build/libs/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xlr-teamcity-plugin
notifications:
  slack:
    secure: Qt2t2omuFxCZchFtWFvQHr1twq/i1u02+/YWK+tcNQg3d5NOUmGUumjiYt7sfugAppiEdagevnwS77ffHLdvCuSUxf+l6aNEx1tXtO9TKB//BxW6o9TdL82P2ILDe5yk6wFm1lZ+aVrWgdgW0CfQOFVnXDwneS9RsUU00/tiCWcOzQbcnOa5FUl1GO55fs8rJ38LCyPCNWC8UqehN5QNJK1uJXrW4MzTiVh0Og3G85JQ6k0lzxcLgrNLGJqcF5v6y3eVO45IQkc140e2Quyh+g1xVFu7KNJplVgCEfwQY/ElEJKdAaS1uvzSdrB/hZE4KJPNv/9q+/Opbi6AnWVfc/XKOaG9zunxiXtDkyvYrvS+N4a5R+4vxCYa2KaonuCiWZZCxVtlZbsZ0xC1gArKkTK7JGuGYUQ18BOW6IIuruA7BtU5XR0PvnxCjeU8HMblycTT/kf4+TYUeWl7MdThuQrALetx/YEGOj54K2wTG81aACc5z58TWbObisGWA143++3DritLEkx9GPCYnTog+7C1aof0bLyHEQwjsEZMC324Nane3UwrmnH9tgBl0oz/lGStrWMlosM5ygKH3flFpQQ6PybxhkefmH4eMKzZWYsYKxBfy9lZkwtJxDuHgHnAFffHNa/XC3dHeqy4hg9BfGLngQ1dXoBya3AFIqaKEpk=
