language: java
notifications:
  hipchat:
    rooms:
      secure: OlIO4DA0xfqdHqS2ytSfDucjIoncHBgLDFjDi1u+qsLOPBeYpYuNJOZkW531yKPFS/na8BjS5WzjrdZW1Wa2I41X2KdNEqOBPxCNsDlvRzEsMUXGCekTEkIaVKgyD8LsAqku+I0CFRsYCQCxRz6yufEenDf7VwdhbM/345mopkI=
deploy:
  provider: releases
  api_key:
  - secure: F10DHW+EFpGbV+bt9U5aMstq3cz0zOrgYrwJmftNZJSajWYTSrI+0O2xvIBp72P9tvWkJnSf+V1YpAwtId3iwreLoUfiWCyUWZF5HZLSlY5CzyuzhDUm2nHnkXYmlsduzGi3AJ7enu3uHohb+al62QM2Fbw1lg2zagERuNWmLxgckCqgc3vZI7q45aWKmFDYO7OTIY57zTktwBVFPKdCSV+lHqMa50qCeHf5z5yK1rUemAh55h5HfZRXjK1m+xHkHw/6AVSKw7dDnqM6cfdm3mUR7TsP8bsCPRbvmgLWRHLzCBTJZy7yP/hsJmsObscbHcW0OR+iK77y45UupekhLKAGYTQ8z7Kpw7GSLlmDdREZG89ImditWMM3fAzTs1ALxVXeecolyC4y7I/ULK9B8y1zQZTFXf5lIEGfbmUce5SNE7NZVOz8cspcJXLopBw3b5Mq1WYUkBsNwVG0OToMqWh551MI2Nf8nHzuJuDWKSt/GjPDLFTJAA/VyyvkMhY1rrO30JJ2heWOfhqNZW3QVA4hsWP02OXUCoXLduz8yMBgjP+PtSqi2xMrc1RVFvI5bSMFJ2FUEkSByEjen51noZ/cGEQL3JG9j25dgpI3ZOXfHhD/eab6yCWYa3NkaVemKV3mBVLH6wmGrvdkYkKvLpcTyhDhVKQnkakMsOJm4cE=
  file: build/libs/xlr-teamcity-plugin-1.0.2.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: false
    repo: xebialabs-community/xlr-teamcity-plugin
env:
  global:
  - secure: F10DHW+EFpGbV+bt9U5aMstq3cz0zOrgYrwJmftNZJSajWYTSrI+0O2xvIBp72P9tvWkJnSf+V1YpAwtId3iwreLoUfiWCyUWZF5HZLSlY5CzyuzhDUm2nHnkXYmlsduzGi3AJ7enu3uHohb+al62QM2Fbw1lg2zagERuNWmLxgckCqgc3vZI7q45aWKmFDYO7OTIY57zTktwBVFPKdCSV+lHqMa50qCeHf5z5yK1rUemAh55h5HfZRXjK1m+xHkHw/6AVSKw7dDnqM6cfdm3mUR7TsP8bsCPRbvmgLWRHLzCBTJZy7yP/hsJmsObscbHcW0OR+iK77y45UupekhLKAGYTQ8z7Kpw7GSLlmDdREZG89ImditWMM3fAzTs1ALxVXeecolyC4y7I/ULK9B8y1zQZTFXf5lIEGfbmUce5SNE7NZVOz8cspcJXLopBw3b5Mq1WYUkBsNwVG0OToMqWh551MI2Nf8nHzuJuDWKSt/GjPDLFTJAA/VyyvkMhY1rrO30JJ2heWOfhqNZW3QVA4hsWP02OXUCoXLduz8yMBgjP+PtSqi2xMrc1RVFvI5bSMFJ2FUEkSByEjen51noZ/cGEQL3JG9j25dgpI3ZOXfHhD/eab6yCWYa3NkaVemKV3mBVLH6wmGrvdkYkKvLpcTyhDhVKQnkakMsOJm4cE=
